version: 2
mergeable:
  - when: pull_request.*
    validate:

    - do: title
      must_exclude:
        regex: ^\[WIP\]
        message: PR is still in progress

    - do: description
      no_empty:
        enabled: true
        message: Description matter and should not be empty. Provide detail with **what** was changed, **why** it was changed, and **how** it was changed.

  - when: schedule.repository
    validate:
      - do: stale
        days: 20
        type: pull_request, issues
    pass:
      - do: comment
        payload:
          body: This is old. Is it still relevant?